package Vista;

import Modelo.Empresa;
import Modelo.EmpresaDAO;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class RegisterDialog extends javax.swing.JDialog {

    Empresa ep = new Empresa();
    EmpresaDAO emp = new EmpresaDAO();
    
    public RegisterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ep = new Empresa();
        initComponents();
        this.setLocationRelativeTo(null);
        nameEmpField.setBackground(new java.awt.Color(0,0,0,1));
        userField.setBackground(new java.awt.Color(0,0,0,1));
        passField.setBackground(new java.awt.Color(0,0,0,1));
        mailField.setBackground(new java.awt.Color(0,0,0,1));
        cifField.setBackground(new java.awt.Color(0,0,0,1));
        phoneField.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        nameEmp = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        nameEmpField = new javax.swing.JTextField();
        cif = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        cifField = new javax.swing.JTextField();
        place = new javax.swing.JLabel();
        placeComboBox = new javax.swing.JComboBox<>();
        user = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        userField = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        passField = new javax.swing.JPasswordField();
        mail = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        mailField = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        phoneField = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGeneral.setBackground(new java.awt.Color(255, 255, 255));
        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameEmp.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        nameEmp.setForeground(new java.awt.Color(255, 255, 255));
        nameEmp.setText("Nombre de la empresa:");
        panelGeneral.add(nameEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panelGeneral.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 10));

        nameEmpField.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        nameEmpField.setForeground(new java.awt.Color(255, 255, 255));
        nameEmpField.setBorder(null);
        nameEmpField.setOpaque(false);
        nameEmpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEmpFieldActionPerformed(evt);
            }
        });
        panelGeneral.add(nameEmpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 215, 30));

        cif.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cif.setForeground(new java.awt.Color(255, 255, 255));
        cif.setText("CIF:");
        panelGeneral.add(cif, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        panelGeneral.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 10));

        cifField.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        cifField.setForeground(new java.awt.Color(255, 255, 255));
        cifField.setBorder(null);
        cifField.setOpaque(false);
        cifField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifFieldActionPerformed(evt);
            }
        });
        panelGeneral.add(cifField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 215, 30));

        place.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        place.setForeground(new java.awt.Color(255, 255, 255));
        place.setText("Localidad:");
        panelGeneral.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        placeComboBox.setEditable(true);
        placeComboBox.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        placeComboBox.setForeground(new java.awt.Color(245, 155, 65));
        placeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione", "A Coruña", "Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila", "Badajoz", "Baleares", "Barcelona", "Burgos", "Cáceres", "Cádiz", "Cantabria", "Castellón", "Ceuta", "Ciudad Real", "Córdoba", "Cuenca", "Girona", "Granada", "Guadalajara", "Gipuzkoa", "Huelva", "Huesca", "Jaén", "La Rioja", "Las Palmas", "León", "Lérida", "Lugo", "Madrid", "Málaga", "Melilla", "Murcia", "Navarra", "Ourense", "Palencia", "Pontevedra", "Salamanca", "Segovia", "Sevilla", "Soria", "Tarragona", "Santa Cruz de Tenerife", "Teruel", "Toledo", "Valencia", "Valladolid", "Vizcaya", "Zamora", "Zaragoza" }));
        placeComboBox.setBorder(null);
        placeComboBox.setOpaque(false);
        panelGeneral.add(placeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 220, -1));

        user.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Nombre de usuario:");
        panelGeneral.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        panelGeneral.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 220, 10));

        userField.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        userField.setForeground(new java.awt.Color(255, 255, 255));
        userField.setBorder(null);
        userField.setOpaque(false);
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        panelGeneral.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 210, 30));

        pass.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Contraseña:");
        panelGeneral.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panelGeneral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 220, 10));

        passField.setBackground(new java.awt.Color(0,0,0,1)
        );
        passField.setFont(passField.getFont().deriveFont(passField.getFont().getSize()+2f));
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.setBorder(null);
        passField.setOpaque(false);
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        panelGeneral.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, 30));

        mail.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("Correo:");
        panelGeneral.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panelGeneral.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 10));

        mailField.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        mailField.setForeground(new java.awt.Color(255, 255, 255));
        mailField.setBorder(null);
        mailField.setOpaque(false);
        mailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailFieldActionPerformed(evt);
            }
        });
        panelGeneral.add(mailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 210, 30));

        phone.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Teléfono:");
        panelGeneral.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        panelGeneral.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 220, 10));

        phoneField.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        phoneField.setForeground(new java.awt.Color(255, 255, 255));
        phoneField.setBorder(null);
        phoneField.setOpaque(false);
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        panelGeneral.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 210, 30));

        register.setBackground(new java.awt.Color(102, 102, 255));
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/registro_1.png"))); // NOI18N
        register.setBorder(null);
        register.setBorderPainted(false);
        register.setContentAreaFilled(false);
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/registro_2.png"))); // NOI18N
        register.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/registro_2.png"))); // NOI18N
        register.setVerifyInputWhenFocusTarget(false);
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        panelGeneral.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 140, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.png"))); // NOI18N
        fondo.setAlignmentX(0.5F);
        panelGeneral.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        getContentPane().add(panelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameEmpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEmpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEmpFieldActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void mailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailFieldActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        if (!"".equals(nameEmpField.getText()) && !"".equals(cifField.getText()) && !"".equals(userField.getText()) && !"".equals(passField.getPassword()) && !"".equals(mailField.getText()) && !"".equals(phoneField.getText())) {
            ep.setNameEmp(nameEmpField.getText());
            ep.setCif(cifField.getText());
            ep.setPlace(placeComboBox.getSelectedItem().toString());
            ep.setUser(userField.getText());
            ep.setPass(String.valueOf(passField.getPassword()));
            ep.setMail(mailField.getText());
            ep.setPhone(Integer.parseInt(phoneField.getText()));
            emp.RegistrarEmpresa(ep);
            JOptionPane.showMessageDialog(null, "Empresa registrada con éxito.");
        } else {
            JOptionPane.showMessageDialog(null, "Los campos están vacíos.");
        }
    }//GEN-LAST:event_registerMouseClicked

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void cifFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cifFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterDialog dialog = new RegisterDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cif;
    private javax.swing.JTextField cifField;
    private javax.swing.JLabel fondo;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel mail;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel nameEmp;
    private javax.swing.JTextField nameEmpField;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel place;
    private javax.swing.JComboBox<String> placeComboBox;
    private javax.swing.JButton register;
    private javax.swing.JLabel user;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
